controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

getLinkForm:
    path: /
    controller: App\Controller\LinkDataController::getLinkForm
    methods: [ GET ]

postLink:
    path: /
    controller: App\Controller\LinkDataController::postLink
    methods: [ POST ]

getLink:
    path: /short/{slug}
    controller: App\Controller\LinkDataController::getLink
    methods: [ GET ]

getLinksList:
    path: /list
    controller: App\Controller\LinkDataController::getLinksList
    methods: [ GET ]

deleteLinks:
    path: /list
    controller: App\Controller\LinkDataController::deleteLinks
    methods: [ POST ]

getDeletedLinksList:
    path: /list/deleted
    controller: App\Controller\LinkDataController::getDeletedLinksList
    methods: [ GET ]

recoverLinks:
    path: /list/deleted
    controller: App\Controller\LinkDataController::recoverLinks
    methods: [ POST ]

